#What is numpy?

In [2]:
##NumPy is a Python library for working with numbers and arrays.

#It lets you do math with many numbers at once.

#It is faster and uses less memory than normal Python lists.

#You can do things like add, multiply, or find the average of arrays.

#It is used a lot in data science and machine learning.

#You can work with big tables of numbers, like in Excel.

#It has tools for advanced math like matrix and linear algebra.

#It can read data from files like .csv.

#It makes coding with numbers easier and cleaner.

#Many other Python libraries are built on top of NumPy.



#import

In [3]:
import numpy as np

#NumPy arrays

In [4]:
#arrays has a dimension(0d 1d 2d 3d 4d ...)
#there are three way to create an array:
# 1: Lists and tuples can transform am array with  "np.array(value)"

# 2:Can create with built-in function so "np.arrange() ,np.alinspace()"

# 3:Create random data so "np.random() module"

In [5]:
arr0d=np.array(53)
arr0d

array(53)

In [6]:
arr1d=np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [7]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3d[0][0]

array([1, 2, 3])

In [11]:
arr3d[0][0][1]

np.int64(2)

#Built-in function


In [12]:
#np.arrange() function creates an array with numbers in a range.
#The function has start end and step paramaters= [start,emd)

In [13]:
import numpy as np
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
#np.linspace() like np.arange but also have how much step paramater.
#End and start point is inclueded

In [17]:
np.linspace(1,29,5,dtype=int)

array([ 1,  8, 15, 22, 29])

In [18]:
np.logspace(1,4,15) #arrange with 10**1 and 10**4,15 numbers with logarithmic increases

array([   10.        ,    16.37893707,    26.82695795,    43.93970561,
          71.9685673 ,   117.87686348,   193.06977289,   316.22776602,
         517.94746792,   848.34289824,  1389.49549437,  2275.84592607,
        3727.59372031,  6105.40229659, 10000.        ])

In [19]:
#an array(10,15,20,25,30)
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [20]:
#an array(0,...,1000) with 26 numbers
np.linspace(0,1000,26,dtype=int)

array([   0,   40,   80,  120,  160,  200,  240,  280,  320,  360,  400,
        440,  480,  520,  560,  600,  640,  680,  720,  760,  800,  840,
        880,  920,  960, 1000])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.eye(5,dtype=int)#create a ones matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
#np.random module provide array has random number

In [27]:
np.random.rand(5)#3 random numbers between 0 and 1

array([0.98223804, 0.21804812, 0.50127954, 0.24728301, 0.50574161])

In [28]:
np.random.rand(2,5)

array([[0.47273302, 0.36226588, 0.27857183, 0.36842737, 0.67483167],
       [0.33679231, 0.55085129, 0.36569251, 0.73850425, 0.68602731]])

In [29]:
np.random.randint(15,67,15)

array([40, 58, 48, 31, 42, 44, 38, 25, 47, 55, 22, 45, 55, 32, 33])

In [30]:
np.random.randint(0,50,(4,6))

array([[36, 31, 15, 26, 17, 31],
       [37,  9, 35, 16,  5, 32],
       [42, 47, 41, 44, 48, 25],
       [13, 36, 33, 35, 18, 36]])

#Controlling the size and shape of arrays

In [31]:
arr0d=np.array(53)
arr1d=np.array([1,2,3,4,5])
arr2d=np.array([[1,2,3],[4,5,6]])
arr3d=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

In [32]:
#.dim attribute: We can look at how many dimensions the arrays have

In [33]:
arr0d.ndim

0

In [34]:
arr1d.ndim

1

In [35]:
arr2d.ndim

2

In [36]:
arr3d.ndim

3

In [37]:
# .shape attribute= to learn array shape

In [38]:
arr2d.shape

(2, 3)

In [39]:
arr3d.shape

(2, 2, 3)

#Accessing and indexing Numpy arrays

In [40]:
arr1d

array([1, 2, 3, 4, 5])

In [41]:
arr1d[0]

np.int64(1)

In [42]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr2d[0]

array([1, 2, 3])

In [44]:
arr2d[1,2]

np.int64(6)

In [45]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[1,1,2]

np.int64(12)

In [47]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [48]:
#example:
ex1=np.arange(53,62)

In [49]:
ex1[4]

np.int64(57)

#Find max , min value in array and accessing the indexs

In [50]:
arr=np.random.randint(1,100,10)
arr

array([83, 34, 47, 22, 83, 84, 18, 41, 57, 17])

In [51]:
arr.max()

np.int64(84)

In [52]:
arr.argmax()

np.int64(5)

In [53]:
arr.min()

np.int64(17)

In [54]:
arr.argmin()

np.int64(9)

#Sliding for NumPy arrays:

In [55]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr[4:10]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
arr[-8:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
arr[2:10:2]

array([3, 5, 7, 9])

In [60]:
arr[3:7]=89 #broadcasting
arr

array([ 1,  2,  3, 89, 89, 89, 89,  8,  9, 10, 11, 12])

In [61]:
#example
arr=np.arange(-30,11)
arr1=arr[5:19]
arr1

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

#Controlling data type of arrays:

In [62]:
# .dtype attribute

In [63]:
arr=np.arange(10)
arr.dtype


dtype('int64')

In [64]:
arr2=np.arange(10,dtype=float)
arr2.dtype

dtype('float64')

# Change dtype of an array

In [65]:
arr=np.array([1.2,3.5,6.6,5.8])
arr.dtype

dtype('float64')

In [66]:
# .astype() method can it

In [67]:
arr.astype(int)

array([1, 3, 6, 5])