#Controlling the shape of an array

In [ ]:
# use .shape
#Shape is the number of items of each dimension

In [ ]:
import numpy as np

In [ ]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.shape

(2, 3)

In [ ]:
arr3d=np.array([[[1,2,3],
                 [4,5,6]],
                [[7,8,9],
                 [10,11,12]]])
arr3d.shape

(2, 2, 3)

#Reshape for an array

In [ ]:
# .reshape()  methodu
#Number of total eleman must be equal, cannot change like (12)=(3,4)=(3,2,2)

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.reshape((3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr3d.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arr3d2=np.arange(30).reshape(3,2,5)
arr3d2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
#We can put -1 for one paramater, if the paramater is unknown

In [ ]:
arr3d3= np.arange(100).reshape(5,-1,5)
arr3d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [ ]:
#Example-1
arrex=np.arange(0,60).reshape(3,4,-1)
arrex

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
arrex.shape

(3, 4, 5)

In [ ]:
arrex.ndim

3

#Flattening Arrays



In [ ]:
#Provide converting a multi-dimensional array to one-dimensional array
# we can use .reshape(-1)

In [ ]:
arr2d.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#Example-2
arrex1=np.arange(30).reshape(5,2,3)
arrex1.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#Iteration for multi-dimensional array

In [ ]:
#for one-dimensional:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in arr1d:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#for multi-dimensional
arr2d=np.arange(12).reshape(3,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in arr2d:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in arr2d:  #not recommended
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
arr3d=np.arange(30).reshape(2,5,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
for i in arr3d:  #not recommended
  for j in i:
    for k in j:
      print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Usage nditer for multi-dimensioan array

In [ ]:
#For loops are not efficient because the number of loops increases with the number of dimensions.
# nditer() is more efficient for that


In [ ]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
np.nditer(arr3d)

In [ ]:
for i in np.nditer(arr3d):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [ ]:
#Examples-3
arrex3=np.linspace(0,120,60,dtype=int).reshape(4,5,3)
arrex3

array([[[  0,   2,   4],
        [  6,   8,  10],
        [ 12,  14,  16],
        [ 18,  20,  22],
        [ 24,  26,  28]],

       [[ 30,  32,  34],
        [ 36,  38,  40],
        [ 42,  44,  46],
        [ 48,  50,  52],
        [ 54,  56,  58]],

       [[ 61,  63,  65],
        [ 67,  69,  71],
        [ 73,  75,  77],
        [ 79,  81,  83],
        [ 85,  87,  89]],

       [[ 91,  93,  95],
        [ 97,  99, 101],
        [103, 105, 107],
        [109, 111, 113],
        [115, 117, 120]]])

In [ ]:
for i in np.nditer(arrex3):
  print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
120


#The four basic operations on arrays

In [ ]:
arr1=np.arange(0,100,10)
arr2=np.arange(1,11)

In [ ]:
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1+arr2

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [ ]:
arr1.__add__(arr2)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [ ]:
arr1-arr2

array([-1,  8, 17, 26, 35, 44, 53, 62, 71, 80])

In [ ]:
arr1.__sub__(arr2)

array([-1,  8, 17, 26, 35, 44, 53, 62, 71, 80])

In [ ]:
arr1*arr2

array([  0,  20,  60, 120, 200, 300, 420, 560, 720, 900])

In [ ]:
arr1//arr2

array([0, 5, 6, 7, 8, 8, 8, 8, 8, 9])

#Calculate the sum,mean,variance and standard deviation of an array

In [ ]:
arr= np.random.randint(0,10,10)
arr

array([2, 9, 3, 0, 0, 7, 0, 4, 2, 9])

In [ ]:
arr.sum()

np.int64(36)

In [ ]:
arr.mean()



np.float64(3.6)

In [ ]:
#Variance shows how much the numbers in a dataset are spread out from the mean(chtgpt)
arr.var()

np.float64(11.440000000000001)

In [ ]:
#Standard deviation is the square root of the variance. It also measures the spread of data(chtgpt)
arr.std()

np.float64(3.3823069050575527)

In [ ]:
np.sqrt(arr)


array([1.41421356, 3.        , 1.73205081, 0.        , 0.        ,
       2.64575131, 0.        , 2.        , 1.41421356, 3.        ])

#Concatenating numpy arrays

In [ ]:
# use .concatenate function , paranaters is ([array1,array2])
#Axis=0(vertical)   Axis=1(horizantal)

In [ ]:
arr1= np.array([10,20,30,70])
arr2=np.array([400,500,600,800])

In [ ]:
np.concatenate([arr1,arr2])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [ ]:
arr1m=np.array([[1,2,3],
                [4,5,6]])
arr2m=np.array([[7,8,9],
                [10,11,12]])

In [ ]:
np.concatenate([arr1m,arr2m],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1m,arr2m],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Stacking numpy arrays

In [ ]:
#Like concatenate but also adds a new axis (dimension)
# use .stack

In [ ]:
arr1m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1m,arr2m],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.stack([arr1m,arr2m])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.stack([arr1m,arr2m],axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [ ]:
#np.hstack()=horizantal stack
#np.vstack()=vertical stack

In [ ]:
np.hstack([arr1m,arr2m])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack([arr1m,arr2m])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Searching index in NumPy arrays

In [ ]:
#To return index of the element we search for
# np.where() has condition paramater

In [ ]:
arr=np.array([1,5,7,4,89,4,5,6,33,65,0])

In [ ]:
np.where(arr==5)

(array([1, 6]),)

In [ ]:
np.where(arr==5,"1","0")

array(['0', '1', '0', '0', '0', '0', '0', '0', '0', '0'], dtype='<U1')

In [ ]:
np.where(arr%2==1,"odd","even")

array(['odd', 'odd', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'odd', 'even'], dtype='<U4')

# Random library for NumPy

In [ ]:
#from numpy import random
import numpy as np

In [ ]:
np.random.randint(low=0,high=10,size=5)

array([3, 9, 3, 0, 1])

In [ ]:
np.random.rand(5) # a random number between 0-1

array([0.63219679, 0.26781827, 0.95309348, 0.10810809, 0.59070344])

In [ ]:
np.random.randn(5)

array([0.1668096 , 0.27092089, 1.13285926, 0.19383386, 0.06466572])

In [ ]:
arr

array([ 1,  5,  7,  4, 89,  4,  5,  6, 33, 65,  0])

In [ ]:
np.random.choice(arr)

np.int64(5)

In [ ]:
np.random.choice(arr,size=3)

array([ 5, 33, 89])

In [ ]:
np.random.choice(arr,size=(3,2))

array([[ 1,  1],
       [ 1, 65],
       [ 1, 65]])